export const BOND_DATA = [
  {
    projectId: "ABC1231",
    title: "Frisco SomeWhat Middle School",
    description:
      "Areas Addressed: Additional Safety & Security, Facility Maintenance, Refresh & Renewal, Recruitment & Retention",
    category: "Security",
    campus: "N/A",
    campusType: "Middle School",
    projectBudget: 26632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 26652000,
    actualCompletion: "MM/DD/YYYY",
  },
  {
    projectId: "ABC1232",
    title: "Independence W. Elementary School",
    description:
      "Areas Addressed: Additional Safety & Security, Facility Maintenance, Refresh & Renewal, Recruitment & Retention",
    category: "Security",
    campus: "N/A",
    campusType: "Elementary School",
    projectBudget: 35632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 37652000,
    actualCompletion: "MM/DD/YYYY",
  },
  {
    projectId: "ABC1233",
    title: "Independence W. High School",
    description:
      "The new school will be located on donated land on the western side of the Texas Medical Center. ",
    category: "New Schools",
    campus: "N/A",
    campusType: "Middle School",
    projectBudget: 35632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 37652000,
    actualCompletion: "MM/DD/YYYY",
  },

  {
    projectId: "ABC1234",
    title: "Custer W. High School",
    description:
      "The new school will be located on donated land on the western side of the Texas Medical Center. ",
    category: "New Schools",
    campus: "N/A",
    campusType: "High School",
    projectBudget: 36632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 36652000,
    actualCompletion: "MM/DD/YYYY",
  },
  {
    projectId: "ABC1235",
    title: "Frisco Elementary School",
    description:
      "Maintain regular preventative maintenance, repair and replacement cycles for buildings",
    category: "Renovation",
    campus: "N/A",
    campusType: "Elementary School",
    projectBudget: 16632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 19652000,
    actualCompletion: "MM/DD/YYYY",
  },
  {
    projectId: "ABC1236",
    title: "Main ST Middle School",
    description:
      "The new school will be located on donated land on the western side of the Texas Medical Center.Projected Cost: $28 million ",
    category: "New Schools",
    campus: "N/A",
    campusType: "Middle School",
    projectBudget: 50632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 50652000,
    actualCompletion: "MM/DD/YYYY",
  },
  {
    projectId: "ABC1237",
    title: "Abraham Lincoln Frisco High School",
    description:
      "Areas Addressed: Additional Safety & Security, Facility Maintenance, Refresh & Renewal, Recruitment & Retention",
    category: "Security",
    campus: "N/A",
    campusType: "High School",
    projectBudget: 21632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 27652000,
    actualCompletion: "MM/DD/YYYY",
  },
  {
    projectId: "ABC1238",
    title: "Navy Frisco High School",
    description:
      "Areas Addressed: Additional Safety & Security, Facility Maintenance, Refresh & Renewal, Recruitment & Retention",
    category: "Security",
    campus: "N/A",
    campusType: "High School",
    projectBudget: 29632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 29652000,
    actualCompletion: "MM/DD/YYYY",
  },
  {
    projectId: "ABC1239",
    title: "Military Frisco High School",
    description:
      "The new school will be located on donated land on the western side of the Texas Medical Center.Projected Cost: $28 million ",
    category: "New Schools",
    campus: "N/A",
    campusType: "High School",
    projectBudget: 23632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 24652000,
    actualCompletion: "MM/DD/YYYY",
  },
  {
    projectId: "ABC1240",
    title: "Waren Universal Middle School",
    description:
      "The new school will be located on donated land on the western side of the Texas Medical Center.Projected Cost: $28 million ",
    category: "New Schools",
    campus: "N/A",
    campusType: "Middle School",
    projectBudget: 30632000,
    isCompleted: false,
    projectCompletion: "MM/DD/YYYY",
    completionPercent: 90,
    finalCost: 30652000,
    actualCompletion: "MM/DD/YYYY",
  },
];
